### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by dcermak**
This is my first try at a German translation. There are a few items that are unfortunately rather clumsy or don't translate very well into German (e.g. "root album" or "home"). Another issue is that "next" and "previous" work very well universally in English, but not that well in German, as "next" and "previous" are used for "next page" or "next photo". However in German you'd say "Nächste**s** Foto" or "Nächste Seite" (mind the additional s in the first phrase). Ideally, these should become two different translatable items.

This fixes https://github.com/dmpop/mejiro/issues/35

### CODE REVIEW

**Comment by hpdorn** [comment]
I think

**img_exif = "Apertur, Belichtungszeit, ISO"**
should be
**img_exif = "Blende, Belichtungszeit, ISO"**

Regards
Hans-Peter

**Comment by dcermak** [comment]
Thanks & done!

**Comment by dmpop** [comment]
Thank you very much for the pull request!

A couple of thoughts from someone, whose German is mediocre at best.

I don't know whether it sounds natural in German, but _Hauptverzeichnis_ for _Root album_ seems fine to me.

> However in German you'd say "Nächstes Foto" or "Nächste Seite"

Yeah, German is not the only language, where this could be a problem. How about something like _Forward_, _Back_, _Start_, _End_? Would that work?

**Comment by dcermak** [comment]
> Thank you very much for the pull request!
> 
> A couple of thoughts from someone, whose German is mediocre at best.
> 
> I don't know whether it sounds natural in German, but _Hauptverzeichnis_ for _Root album_ seems fine to me.
> 
> > However in German you'd say "Nächstes Foto" or "Nächste Seite"
> 
> Yeah, German is not the only language, where this could be a problem. How about something like _Forward_, _Back_, _Start_, _End_? Would that work?

_Start_ & _End_ would work, but imho _Forward_ & _Back_ would sound quite odd in German: vorwärts, rückwärts/zurück. I personally have never heard either of the terms in the context of switching through pages/photos/albums.

**Pull request merged**
